train:
  batch:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: src.transforms.BackgroundSampler
        dataset_size: ${dataset.train.num_samples}
        batch_size: ${dataloader.train.batch_size}
      - _target_: src.transforms.NoiseScheduler
        dataset_size: ${dataset.train.num_samples}
        batch_size: ${dataloader.train.batch_size}

inference: null
