basis:
  _target_: src.model.basis.BasisSet
  model_type: baseline
  model_cfg:
    input_dim: ${dataset.dim}
    hidden_dims: [20, 1000]
    activation: relu
    init_mode: null
  dtype: ${dataset.dtype}
