train:
  _target_: torch.utils.data.DataLoader
  batch_size: 500
  num_workers: 0
  pin_memory: true
  shuffle: true
  drop_last: true
  worker_init_fn:
    _target_: hydra.utils.get_method
    path: src.utils.init.set_worker_seed
  collate_fn:
    _target_: src.dataset.collate.collate_fn
    use_label: ${dataset.use_label}
